/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#ccc3d6",
        "on-primary-fixed-variant": "#591db3",
        "inverse-primary": "#713dcc",
        "surface-dim": "#10141a",
        "primary-container": "#8957e5",
        "secondary-fixed-dim": "#7bdb80",
        "background": "#10141a",
        "on-secondary-fixed": "#002106",
        "tertiary-fixed": "#ffdad6",
        "on-secondary": "#00390e",
        "primary": "#d3bbff",
        "outline": "#958d9f",
        "error-container": "#93000a",
        "surface-bright": "#353940",
        "on-surface": "#dfe2eb",
        "tertiary-fixed-dim": "#ffb4ac",
        "outline-variant": "#4a4453",
        "secondary-fixed": "#97f999",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#262a31",
        "inverse-surface": "#dfe2eb",
        "tertiary": "#ffb4ac",
        "inverse-on-surface": "#2d3137",
        "on-primary": "#3f008d",
        "on-tertiary-fixed-variant": "#93000e",
        "surface": "#10141a",
        "primary-fixed": "#ebddff",
        "on-error": "#690005",
        "on-tertiary-container": "#fffdff",
        "on-background": "#dfe2eb",
        "error": "#ffb4ab",
        "surface-container": "#1c2026",
        "on-primary-fixed": "#250059",
        "on-primary-container": "#fffdff",
        "tertiary-container": "#da3633",
        "surface-variant": "#31353c",
        "secondary": "#7bdb80",
        "surface-container-lowest": "#0a0e14",
        "on-secondary-container": "#91f294",
        "primary-fixed-dim": "#d3bbff",
        "secondary-container": "#007124",
        "on-tertiary-fixed": "#410003",
        "surface-tint": "#d3bbff",
        "surface-container-highest": "#31353c",
        "on-tertiary": "#690007",
        "surface-container-low": "#181c22",
        "on-secondary-fixed-variant": "#005319"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "4px",
        gutter: "16px",
        "container-max": "1600px",
        md: "16px",
        lg: "24px",
        xl: "32px"
      },
      fontFamily: {
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        display: ["Space Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-sm": ["JetBrains Mono", "monospace"],
        code: ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["44px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        code: ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
